spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

cors:
  allowed-origins: http://localhost:5173,http://localhost:3000,http://54.226.164.38

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevEnvironmentChangeInProduction1234}
  expiration: ${JWT_EXPIRATION:86400000}